{{- if .Values.checkWalArchive.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "barman.fullname" . }}-check-wal
  labels:
    {{- include "barman.labels" . | nindent 4 }}
    app.kubernetes.io/component: check-wal
spec:
  schedule: {{ .Values.checkWalArchive.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- include "barman.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: check-wal
        spec:
          restartPolicy: Never
          serviceAccountName: {{ include "barman.serviceAccountName" . }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: check-wal
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["/bin/bash", "/scripts/check-wal.sh"]
              env:
                {{- include "barman.env" . | nindent 16 }}
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: scripts
              configMap:
                name: {{ include "barman.fullname" . }}-scripts
                defaultMode: 0755
{{- end }}
