{{- if .Values.credentials.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "barman.fullname" . }}-credentials
  labels:
    {{- include "barman.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.credentials.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.credentials.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.credentials.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "barman.fullname" . }}-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range $key, $ref := .Values.credentials.externalSecret.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $ref.key | quote }}
        property: {{ $ref.property | quote }}
    {{- end }}
{{- end }}
