{{- if and .Values.ssh.enabled .Values.ssh.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "barman.fullname" . }}-ssh
  labels:
    {{- include "barman.labels" . | nindent 4 }}
type: Opaque
stringData:
  id_rsa: |
{{ .Values.ssh.secret.privateKey | indent 4 }}
  id_rsa.pub: |
{{ .Values.ssh.secret.publicKey | indent 4 }}
  known_hosts: |
{{ .Values.ssh.secret.knownHosts | indent 4 }}
{{- end }}
